In [1]:
import numpy as np

# 3x3 Grid → states 0 to 8
rows, cols = 3, 3
gamma = 1.0
theta = 1e-6

treasure = 8
snakes = [3, 4, 7]

actions = ['U','D','L','R']

V = np.zeros(9)

while True:
    delta = 0
    newV = V.copy()

    for s in range(9):

        if s == treasure:
            continue

        r, c = divmod(s, cols)
        action_values = []

        for a in actions:

            # --- Transition P(s' | s,a) ---
            if a == 'U':
                r2, c2 = max(r-1,0), c
            elif a == 'D':
                r2, c2 = min(r+1,rows-1), c
            elif a == 'L':
                r2, c2 = r, max(c-1,0)
            elif a == 'R':
                r2, c2 = r, min(c+1,cols-1)

            s_next = r2*cols + c2

            # Deterministic → P = 1 for s_next
            prob = 1.0

            # Reward
            if s_next == treasure:
                R = 10
            elif s_next in snakes:
                R = -10
            else:
                R = -1

            # --- FULL Bellman Summation ---
            total = prob * (R + gamma * V[s_next])

            action_values.append(total)

        newV[s] = max(action_values)
        delta = max(delta, abs(newV[s] - V[s]))

    V = newV
    if delta < theta:
        break

# Extract Policy
policy = []
for s in range(9):
    if s == treasure:
        policy.append('T')
        continue

    r, c = divmod(s, cols)
    best_action = None
    best_value = -1e9

    for a in actions:

        if a == 'U':
            r2, c2 = max(r-1,0), c
        elif a == 'D':
            r2, c2 = min(r+1,rows-1), c
        elif a == 'L':
            r2, c2 = r, max(c-1,0)
        elif a == 'R':
            r2, c2 = r, min(c+1,cols-1)

        s_next = r2*cols + c2

        if s_next == treasure:
            R = 10
        elif s_next in snakes:
            R = -10
        else:
            R = -1

        value = R + gamma * V[s_next]

        if value > best_value:
            best_value = value
            best_action = a

    policy.append(best_action)

print("Optimal Values:")
print(V.reshape(3,3))

print("\nOptimal Policy:")
print(np.array(policy).reshape(3,3))


Optimal Values:
[[ 7.  8.  9.]
 [ 6.  9. 10.]
 [ 0. 10.  0.]]

Optimal Policy:
[['R' 'R' 'D']
 ['U' 'R' 'D']
 ['R' 'R' 'T']]
